### ISSUE TITLE
OIDC provider support

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#10056]
## Description

Provide a generic OIDC provider support

```[tasklist]
### Tasks
- [x] Merge PR https://github.com/geosolutions-it/geostore/pull/330
- [x] Merge PR https://github.com/geosolutions-it/geostore/pull/357
- [x] add the configurations to `spring-security-context.xml` (see Other information)
- [x] document the change above in migration guidelines
- [x] document the configuration of OIDC provider.
- [ ] backport all PRs above
```

## Other information

Here the configurations to add to spring security context, following the ones of geostore.

-  `<bean id="oidcSecurityConfiguration" class="it.geosolutions.geostore.services.rest.security.oauth2.openid_connect.OpenIdConnectSecurityConfiguration"/>` [here](https://github.com/geosolutions-it/geostore/pull/330/files#diff-44c464d871cfc27eccef59da6d9bb0ce6ceeac4fda004eaf9349c28f808ea2d0R50-R51)
	- `<security:custom-filter ref="oidcOpenIdFilter" after="BASIC_AUTH_FILTER"/>` [here](https://github.com/geosolutions-it/geostore/pull/330/files#diff-44c464d871cfc27eccef59da6d9bb0ce6ceeac4fda004eaf9349c28f808ea2d0R30)

**Comment by tdipisa** [comment]
@ElenaGallo @tdipisa and @offtherailz will test this
