### ISSUE TITLE
Improve Plugin documentation

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#2305]
Many plugins lack documentation or the available documentation is insufficient.

As a MapStore2 "configurator" I need to know what are the different plugin requirements and configuration options.

**Comment by offtherailz** [comment]
See this issue : https://github.com/geosolutions-it/MapStore2/issues/3845

**Comment by offtherailz** [comment]
Here a report of plugins and pages that still need to be documented or need a check

### Plugins

#### Missing documentation

- [ ] AddGroup
- [ ] BurgerMenu
- [ ] Cookie
- [ ] Dashboard
- [ ] DashboardEditor
- [ ] Dashboards
- [ ] ExpanderPlugin
- [ ] History
- [ ] Home
- [ ] Language
- [ ] MapExport
- [ ] MapFooter
- [ ] MapImport
- [ ] MapLoading
- [ ] OmniBar
- [ ] Redirect
- [ ] Save
- [ ] SaveAs
- [ ] Settings
- [ ] ShapeFile
- [ ] Snapshot
- [ ] ThemeSwitcher <-- used/maintained anymore ?
- [ ] Toolbar
- [ ] ZoomAll

#### plugins to check

- [ ] FeatureGrid <-- Replaced by FeatureEditor
- [ ] FloatingLegend <-- Documented but not used anymore
- [ ] RasterStyler <-- Remove, replaced by StyleEditor (used in examples)
- [ ] Styler <-- Remove, replaced by StyleEditor (used in examples)
- [ ] VactorStyler <-- Remove, replaced by StyleEditor
- [ ] RulesManagerFooter <-- Check if needed anymore
- [ ] Help ??? not sure is used
- [ ] Create an alias for MetadataExplorer as CatalogPlugin

### Pages

#### Missing documentation
- [ ] Maps
- [ ] MapViewer
- [ ] Dashboard
- [ ] Manager <-- to document
- [ ] Importer <-- Documented, Needs a renew of style before to be officially release
