### ISSUE TITLE
Implement Geodashboard

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2622]
### Description
As for the [mockup](https://demo.geo-solutions.it/mockups/mapstore2/#/dashboard)

### Depends On (optional)
 - TBD mapstore's related issues
### Please indicate if this issue is related to a bug or a new feature request
- [ ] Bug
- [x] New Feature

### Acceptance Criteria - AC

As a user I want to be able to edit a dashboard. A dashboard is a page of information (charts, text, maps and tables) that the user can create edit, share and delete.
 - The dashboard widgets available must be: 
 - charts of the following types
   - pie
   - bar
   - line
   - gauges (a review is needed)
 - Text 
 - Maps, importable as existing MapStore maps
 - Tables
 - The dashboard should support embedding (for the future)

The widgets should interact with the following options 
 -  filter data by 1 current map viewport
 - (future) filter by item selection 

### Tasks 
 - [x] connected to #2592 : Text Widget
 - [x] connected to #2593 : Base Scheleton
 - [x] connected to #2623 : table widget
 - [x] connected to #2642 : counter widget
 - [x] connected to #2661  : map widget 
 - [x] connected to #2754  : map widget editing
 - [x] connected to #2662 : support to map connections
 - [x] connected to #2660  : support to save/restore dashboards
 - [x] connected to #2663 : support for edit/view mode of dashboard. 
 - [x] connected to #2664 : browse existing dashboards (should be merged with existing maps)
### Needed Fixes
 - [x] connected to #2618 - Issues showing the catalog
 - [x] connected to #2673 - Unable to go back from Widget selection
 - [x] connected to #2674 - Missing Tooltip
