### ISSUE TITLE
Minor Release 2018.01.01

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#2713]
### Description
-  [Release branch](https://github.com/geosolutions-it/MapStore2/tree/2018.01.01)

Minor release with following fixes: 
 - [x] #2580, #2585, #2595, #2604 - plugin example
 - [x] #2588 - Readme update
 - [x] #2599 - Layer visibility fix
 - [x] #2644 support for onlink handler
 - [x] #2547 - Openlayers version update to version 4.6.4
 - [x] #2579 - UTF-8 encoding
 - [x] #2562 - German translation of the cookies fragments
 - [x] #2668 - Precision of query panel details panel
 - [x] #2685 IE fixes with openlayers maps
 - [x] maybe #2699 - I.E. caching issues fixes

TODO: add release checklist
