### ISSUE TITLE
GeoDashboard DEV Review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#2790]
### Description
the tasks below should be part of the first geodashboard release:

- [x] If I cannot use a layer for a specific widget the tooltip containing the warning must appears immediately and the icon must be properly changed using the standard one (triangle + exclamation mark)
- [x] Remove the gauge widget from configuration
- [x] #2673 - The wizard must allows to go back to the previous step (not only the next one) 
- [x] Vertical and Horizontal align of the number inside the counter widget
- [x] #2768 - Allow creating a map starting from an empty one
- [x] The table widget must show a proper message when empty
- [x] Sometime when panning a map some charts in the widget list are redrawn
- [x] Improve the titles in wizard

Bugs revealed during testing:
 - [x] edit existing map doesn't update the map position.  #2794
 - [x] Maps with google background sometime fail #2786 
 - [x] selecting chart widget and a layer in the Widget Catalog you can proceed without selecting a Chart type, the result configuring chart options is that you have a line chart by default and this description fields:
![immagine](https://user-images.githubusercontent.com/33256901/38417189-a640c976-3997-11e8-8046-e648f014875f.png)
