### ISSUE TITLE
Improve project creation and build process

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3168]
### Description
After creating the project C126 following issues has been detected, they are related to the standard project creation and build processes:
- [ ] missing themePrefix https://github.com/geosolutions-it/MapStore2-c126/issues/10
- [ ] missing version https://github.com/geosolutions-it/MapStore2-c126/issues/5
- [ ] missing translations https://github.com/geosolutions-it/MapStore2-c126/issues/4
- [x] docker files missing see https://github.com/geosolutions-it/MapStore2/issues/3450
- [ ] print installation issues
https://github.com/geosolutions-it/MapStore2-c126/issues/9
https://github.com/geosolutions-it/MapStore2-c126/issues/2
- [ ] order of html template in pom.xml https://github.com/geosolutions-it/MapStore2/issues/3168#issuecomment-466409492
- [ ] share api template pom.xml https://github.com/geosolutions-it/MapStore2/issues/3168#issuecomment-466409492
- [x] Standard Template Build problems, requires #3589
- [ ] "standard" project template produces wrong links to resources, requires #3388 
- [ ] Improvements for create project script and/or Standard files, requires #3098 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- It's not dependent on browser

*Steps to reproduce*

- create a new standard project

*Expected Result*

- standard project should start with the correct configuration

*Current Result*

- application doesn't work because of some configuration issues

### Other useful information (optional):

Verify all modes: desktop, mobile, embedded and api.

**Comment by offtherailz** [comment]
Take also a look to  : 
 - localConfig.json ( spatialFilter may contain BBox geometric operation, that is not supported anymore).
 - proxy.properties

**Comment by allyoucanmap** [comment]
pom.xml must have following excutions in this order:

- `<id>only index.html</id>`
- `<id>only embedded.html</id>`
- `<id>only api.html</id>`
- `<id>html, configuration files and images</id>`

if `<id>html, configuration files and images</id>` is placed first,
html themplates with version will not be overrided in the .war file.

ShareApi plugin needs a template to show the code in a textarea

![share-api-panel](https://user-images.githubusercontent.com/19175505/53247366-76b30380-36b3-11e9-8dbf-b7aa4caeebb5.png)

the [template](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/share/api-template.raw) has some hardcoded info (eg: the .js file name)
so the template is not valid if the project create an api js file with custom name

**Comment by tdipisa** [comment]
Closed in favor of #6314
