### ISSUE TITLE
Test GeoServer Setup

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3200]
### Description
A GeoSolutions's GeoServer instance for testers needs to be set up. We need at least the following installed in our environment:

- [ ] Latest stable version of GeoServer
- [ ] Latest stable version of GeoFence
- [ ] PostgreSQL/PostGIS
- [ ] Auth/Auth integration with MS2 instances (QA, DEV) through authkey

**Comment by simboss** [comment]
[This](https://docs.google.com/drawings/d/1Nb_a9JDhtvpokDgZTneiuKOI-uYpKeW2et5XDvbsDhY/edit) is our plan.

**Comment by casualuser** [comment]
according to the deployment plan and initial comments we need here the following resources accessible:

- [] parent of #3653 - repo for Test GeoServer Setup required
- [] parent of #3654 - access to Jenkins at build2.geo-solutions.it for Test GeoServer Setup required
- [] parent of #3655 - access to Postgress dbms.geo-solutions.it for Test GeoServer Setup required
- [] parent of #3655 - dns A record for gs-stable.geo-solutions.it required for Jenkins named build2
