### ISSUE TITLE
Improve Date/Time/DateTime ColumnFilter in FeatureGrid

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3586]
# Description
Now column filters of the feature grid have a minimal support for date/time and datetime values. 
 - Do not allow > < = <>(!=) filters, filter only on equal date
 - The data inserted by the user is inteded in his datetime, not UTC.

We should improve it to align with functionalities of number filters and so, support better data text insert.  

### Acceptance Criteria
 - User should be able to insert manually date time, intended as UTC
 - Format of writing should be configurable, depending on user's locale and shown as hint in the placeholder
 - User can insert an operator (> < = <>) before the date to change the filter accordingly (intended as attribute > date_written)
 - The user can use the picker to insert the date/time/datetime
 - User can reset the filter clearing the text
 - TBD - Default insert date format for date/time/datetime

### Tasks
- [ ] Improve text datetime insert functionalities (now user can insert data in his browser's language format). 2PT
- [ ] Allow opearators >, <, =, !=(<>) operators ( requires to improve format and insert ) 1PT
- [ ] Fix issues with data insert
  - with datetime attribute, if you insert only the date, the time will be the current hour, instead it should be 00:00:00 1PT
- [ ] Fix data insert to use UTC (now current browser's time, e.g. GMT+1, then converted in UTC). 1PT
