### ISSUE TITLE
Viewer example application

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#36]
Implement a viewer application with the available components:
 - [x] leaflet map (#28)
 - [x] openlayers map (#98)
 - [x] background and WMS layers (#29)
 - [x] background switcher(#114)
 - [x] layertree (#35)
 - [x] legend (#151)
 - [x] help / credits / about (#34)
 - [x] interactive help (#155)
 - [x] dynamic config loading (#31)
 - [x] I18N (#32)
 - [x] GetFeatureInfo (#86)
 - [x] Advanced GetFeatureInfo (#153)
 - [x] NavigationHistory (#156)
 - [x] Overview (#157)
 - [ ] Print (#158)
 - [x] Measure (#154)
 - [x] Locate Me (#144)
 - [x] Loading spinner (#108)
 - [x] Zoom all (#102)
 - [x] Scalebar (#87)

**Comment by mbarto** [comment]
Print will be delayed to a future release.
