### ISSUE TITLE
User Guide Update for new features

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3622]
### Description
Since some new features have been introduced in master, the user guide needs to be updated.

### Other useful information (optional):

The new tools/functionalities/updates to document are the following:

- [x] Update doc related to the layer filtering (see #3785)
- [x] Search Tool updates (consider to review the doc related to the  WFS custom services that has been moved from Settings) Parent of #3523
- [x] Catalog tool updates #3824 
- [x] Tooltip settings in layer properties Parent of  #3608 
- [x] Info tool with input coordinates Parent of #3548
- [x] New annotations tool #3715 
- [x] CRS selector tool #3716 (**only on master for this release 2019.02.00**)
