### ISSUE TITLE
MapStore Data Directory

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4670]
## Description
The MS deploy must be improved including a MapStore Data Directory. By default the data directory can be internal but the possibility to externalize it will be implemented in MS. What has been done for geOrchestra [here](https://github.com/georchestra/mapstore2-georchestra/pull/121) can be properly reviewed to be included in MS according to this requirements. Below all the elements that need to be extenalized within a data directory (they are mandatory):

- [x] **GeoStore configuration properties**: it can be already externalized through a Java environment variable
- [x] **Http-Proxy configuration properties**: the proxy has ben [recently improved](https://github.com/geosolutions-it/http-proxy/pull/49) for geOrchestra so now its configuration properties can be externalized
- [x] **MapStore localConfig file**: an [issue](https://github.com/geosolutions-it/MapStore2/issues/3688) already exists for this and connected to this issue as dependency
- [ ] **Annotation symbols**: MS default and custom list of symbols can be externalized in the MS's data directory
- [x] **Print Configuration**: externalize the config JAML file and PDF output directory (issue [here](https://github.com/geosolutions-it/MapStore2/issues/3119) is related and it has been put as a dependency of this issue)

- [x] **Installed extensions**

This work must also include the related DEV guide update to explain:
- Why the Data Directory is needed
- How it works and how it can be configured 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [X] CI related changes
- [X] Other... Please describe: related DEV guide updates

## Other useful information
The location of the MS Data Directory will be externalized through a Java environment variable.

**Comment by tdipisa** [comment]
With the current implementation the MS data dir can be used only inside a MS's project (the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/)).
The idea is anyway to enable it also for the MS product by including a new data directory in the project that contains all the involved configurations (this will be the default data directory).

**Comment by offtherailz** [comment]
Closing in favor of https://github.com/geosolutions-it/MapStore2/issues/7165
