### ISSUE TITLE
User Extensions

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4722]
## Description
Add user extensions plugin for contexts. This plugin allows to enable / disable plugins defined as userPlugins when creating a context.

## Acceptance criteria
- The user extensions plugin can be added from context creator. 
- When a context contains this plugin, an entry in burger-menu is added, called "User Extensions"
- When the user clicks on "user extensions" a list of plugins is shown
- plugins marked as "user plugins" are listed (flat list), checked accordingly with the "default enabled" checkbox configured in the original context by the administrator
- Title description and symbology of these entries should be the same of the context creator
- if the user click on one of these entries, the related plugin is added to the map

Development of user-extensions in two phases: 
1st phase: 
1. develop base plugin so we can start to try it and find out issues or pliugins to modify (#4720 )
2.  refine titles, descriptions, symbologies and clean up plugins list (#4721 )

### Other Minor fixes required:

- [x]  TOC should contain plugins to add functionalities like AddLayer, FilterLayer... (#4719 ):  

- [x] Drawer Menu add/remove together with `TOC` (#4698)

- Map footer fixes: 
    - [x]  `MapFooter` enable|disable do not  update immediately (#4732)

**Comment by offtherailz** [comment]
exclude MapFooter at this stage and make it compatible with georchestra too it's hard. It's strictly related with all the issues with Layout renew, therefore solving this issue means do the layout renew.

For this reason I suggest to make the footer mandatory plugin, at this stage (it's also needed to show attribution. 
@tdipisa please tell me if you agree with me. 

I'll proceed to check issues with not instanly rendered plugins.
