### ISSUE TITLE
Application Context Plugins

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4774]
## Description
Adds the ability to add and configure plugins in application contexts

## Acceptance criteria

- [ ] backend and base configuration support [mapstore2-georchestra/#20](https://github.com/georchestra/mapstore2-georchestra/issues/20)
- [ ] frontend part [mapstore2-georchestra/#22](https://github.com/georchestra/mapstore2-georchestra/issues/22)

**Comment by francoperversi** [comment]
@vlt1 @tdipisa @offtherailz The following issues were noticed in plugins configuration:
1. - [ ] It is possible to insert the plugin `Map Details` that allows to see map details but it is actually impossible to add details for contexts. If we don't want to improve application contexts adding details to them, we should remove the possibility to add this plugin
2. - [ ] The `Query panel` plugin should probably be hidden from plugin list, and should be enabled by default when others plugins that use the Query panel are added (like Attribute Table, layer filter, Widgets). There's probably a problem related to `Query panel` plugin because sometimes it enables adding the `List of Layers` plugin and sometimes does not). Morover I can add this plugin alone also if it depends from other plugins.
3. - [ ] `Style Editor` plugin what is it for? Seems that nothing change adding or not this plugin (if this plugin serves to create new styles it doesn't work). Moreover this plugin can be added alone, also if it probably depends from TOC and from layer settings
4. - [ ] `Widgets` plugin should depends from `List of Layers` plugin, but I can actually add it alone
Morover was noticed that in step 3 of the wizard (Configure Map), clicking on `Reload Map` button, the modal window that opens is draggable vertically (why?) and the X button is in lowercase. If I click outside the window, it closes.

**Comment by tdipisa** [comment]
In addition I found the following to take into account:

- [ ] The show metadata option should be disabled by default, so the related button in TOC toolbar does not appears

- [ ] If I add undo/redo plugins nothing appears in the viewer: buttons are not present in nav toolbar. Only adding the expander plugin these are available. We should at least set up a dependency in configuration and make the expander plugin hidden to be automatically added when needed.

- [ ] Contexts with read permissions to everione are not accessible (HTTP 404). Related to https://github.com/geosolutions-it/geostore/issues/202

**Comment by francoperversi** [comment]
Some additional points below:

- [ ] In "Version" plugin the description is "Show Mapstore Version in settings window" but in Georchestra the version showed is the Georchestra one

- [ ] Adding Map Templates, Burger Menu is not added together

- [ ] Adding "Save" plugin, the Burger Menu is added together but after the save option is not present in the Menu

- [ ] Adding "Save as" plugin, the Burger Menu is added together but after the save as option is not present in the Menu

**Comment by tdipisa** [comment]
Closed in favor of #155.
