### ISSUE TITLE
geOrchestra in User Guide

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5060]
## Description

An improvement of the user guide is necessary with the addition of a Managing Contexts section and its sub-sections as follows:
- [x] Overview (Managing context button, New Context button)
- [x] Application context ( Three step of the wizard [#18](https://github.com/georchestra/mapstore2-georchestra/issues/18), [#171](https://github.com/georchestra/mapstore2-georchestra/issues/171) )
- [x] Extension manager ([#13](https://github.com/georchestra/mapstore2-georchestra/issues/13))
- [x] Map Catalog ( [#59](https://github.com/georchestra/mapstore2-georchestra/issues/59), #4460)
- [x] Map Templates ( [#151](https://github.com/georchestra/mapstore2-georchestra/issues/151) )

An update is required for thiese sections:
- [x] Identify tool improvement ([#44](https://github.com/georchestra/mapstore2-georchestra/issues/44))
- [x] Advanced Measurement tool ([#51](https://github.com/georchestra/mapstore2-georchestra/issues/51))
- [x] Updates to the Locate User tool ([#53](https://github.com/georchestra/mapstore2-georchestra/issues/53))

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

**Comment by ElenaGallo** [comment]
> - [x] Identify tool improvement ([#44](https://github.com/georchestra/mapstore2-georchestra/issues/44))
> - [x] Advanced Measurement tool ([#51](https://github.com/georchestra/mapstore2-georchestra/issues/51))
> - [x] Updates to the Locate User tool ([#53](https://github.com/georchestra/mapstore2-georchestra/issues/53))

The improvements above have been updated in #4946.
