### ISSUE TITLE
Clean up api Example

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#5143]
## Description
API example has the Identify plugin configured, but it is not included in the plugins list.
https://github.com/geosolutions-it/MapStore2/tree/master/web/client/examples/api 

# Tasks 
- [ ] Verify the list of plugins configured and ensure that it matches with the effective plugins available. 
- [ ] explain this condition in the example code comment, so it's easy for a reader how to add/remove plugins
- [ ] make clear the scope of the example (maybe adding more developer documentation about JS API.

**Comment by offtherailz** [comment]
I tried to add the Identify Tool to the example using this
``'diff
diff --git a/web/client/examples/api/localConfig.json b/web/client/examples/api/localConfig.json
index 7ffc74dfc..f0977b575 100644
--- a/web/client/examples/api/localConfig.json
+++ b/web/client/examples/api/localConfig.json
@@ -1,5 +1,5 @@
 {
-       "proxyUrl": "/mapstore/proxy/?url=",
+       "proxyUrl": "../../proxy/?url=",
        "geoStoreUrl": "/mapstore/rest/geostore/",
   "printUrl": "https://demo.geo-solutions.it/geoserver/pdf/info.json",
        "bingApiKey": "AhuXBu7ipR1gNbBfXhtUAyCZ6rkC5PkWpxs2MnMRZ1ZupxQfivjLCch22ozKSCAn",
diff --git a/web/client/examples/api/plugins.js b/web/client/examples/api/plugins.js
index e899f93a6..2d10f0164 100644
--- a/web/client/examples/api/plugins.js
+++ b/web/client/examples/api/plugins.js
@@ -9,6 +9,7 @@
 module.exports = {
     plugins: {
         MapPlugin: require('../../plugins/Map'),
+        Identifylugin: require('../../plugins/Identify'),
         ToolbarPlugin: require('../../plugins/Toolbar'),
         DrawerMenuPlugin: require('../../plugins/DrawerMenu'),
         SnapshotPlugin: require('../../plugins/Snapshot'),
```
and accessing to 
```
http://localhost:8081/examples/api/?debug=true&config=../plugins/config.json
```
To use a layer and check the Identify functionality but the identify panel do not trigger.

We should investigate on this and document if any additional configuration is needed in this case.

**Comment by vlt1** [comment]
@offtherailz After investigating the problem with Identify plugin I've found that react-dock that is used throughout the project for Dock panel, positions these panels relative to the browser window, not the container, which results in incorrect placement of dock panels(in the api example Identify plugin is present but completely obscured by the side panel "Embed MapStore2 in your website"). The solution here I think is to drop the library and develop a custom component that will place elements correctly, respecting the bounds of the container div.

**Comment by allyoucanmap** [comment]
@offtherailz @vlt1 

> @offtherailz After investigating the problem with Identify plugin I've found that react-dock that is used throughout the project for Dock panel, positions these panels relative to the browser window, not the container, which results in incorrect placement of dock panels(in the api example Identify plugin is present but completely obscured by the side panel "Embed MapStore2 in your website"). The solution here I think is to drop the library and develop a custom component that will place elements correctly, respecting the bounds of the container div.

I don't think this issue is completely related to the position of panels even if I agree we should drop the `react-dock` library. 
In this case we could use the `size` and `fluid` cfg options of Identify to ensure the panels is rendered in the target container.

## Use local storage plugin configuration

I followed these steps:

- created and saved a configuration in the plugins example as suggested in the api example description

![image](https://user-images.githubusercontent.com/19175505/91710028-e72dc100-eb83-11ea-9121-dbf318b34312.png)

screenshot of plugins example page where I selected following plugins: Map, Toolbar and Identify, then I saved this configuration as `identify`

![image](https://user-images.githubusercontent.com/19175505/91709853-a9309d00-eb83-11ea-9582-d5149feb3273.png)

- opened the api example using the previously saved map name http://localhost:8081/examples/api/?map=identify

screenshot of api example with the identify configuration
![image](https://user-images.githubusercontent.com/19175505/91710332-5dcabe80-eb84-11ea-8082-3b47802fc9ff.png)


## Use default plugin configuration

If we want to have the Identify by default we should update also the default configuration in the [init.js](https://github.com/geosolutions-it/MapStore2/blob/87315ac2e09382cc4a41417f76ff9b25c2fa4b46/web/client/examples/api/init.js#L15-L51) including the identify one, eg:

```js
embeddedPlugins = {
        "desktop": [
            "Map",
            "MousePosition",
            "Toolbar",
            "ZoomAll",
            "Expander",
            "ZoomIn",
            "ZoomOut",
            "ScaleBox",
            "OmniBar",
            "Search",
            "DrawerMenu",
            "TOC",
            {
                "name": "BackgroundSelector",
                "cfg": {
                    "dimensions": {
                        "side": 65,
                        "sidePreview": 65,
                        "frame": 3,
                        "margin": 5,
                        "label": false,
                        "vertical": true
                    }
                }
            },
            {
                "name": "TOCItemsSettings",
                "cfg": {
                    "width": 300,
                    "showFeatureInfoTab": false
                }
            },
            "FullScreen",
            {
                "name": "Identify", // New configuration
                "cfg": {
                    "showFullscreen": false,
                    "dock": true,
                    "position": "right",
                    "size": 0.4,
                    "fluid": true,
                    "viewerOptions": {
                        "container": "{context.ReactSwipe}"
                    }
                }
            }
        ]};
```
