### ISSUE TITLE
User Guide - Exploring Maps section updating

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5887]
## Description

Implementation of the Exploring Maps section with the follows issue:

- [x] #5603 on Layer Settings section
- [x] #5522 on  Adding Annotations section
- [x] #3425 on  Layer Settings  and Catalog Services sections

*Documentation section involved*
- [x] User Guide
- [ ] Developer Guide

**Comment by tdipisa** [comment]
@ElenaGallo which is the status of this?

**Comment by ElenaGallo** [comment]
@tdipisa is still in progress and I am waiting for  [this](https://github.com/geosolutions-it/MapStore2/issues/5681#issuecomment-707892016) issue to be merged to properly update the style editor on the userguide
