### ISSUE TITLE
Various improvements/fixes for Maps Embedding

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#6643]
## Description
I have played a little with Maps embedding as IFrame, here below suggestions:
- [ ] If you open [this page](https://www.geosolutionsgroup.com/technologies/mapstore/) and scroll to the bottom there is a MapStore map embedde; in incognito I noticed that embedding does not work. Ok, maybe it is normal that it does not work but at least give me a nice message. That said, I don't think it should simply crash like this, we have got to make it work.
- [ ] Same map as above, I click on the icon to open it in a larger window and boom "Ops, Something has gone wrong.", nice...
- [ ] if you check what you can do with other populare similar services we are way behind. If you check what uMap can do (see at the bottom of [this](https://www.geosolutionsgroup.com/partnership/) page), there is room for improvement:
- **IMPORTANT** we shall be able to disable muse scrolling and add zoom in/out as the scrolling makes it difficult to embed in some pages
- we need the fullscreen button
- we shall make it possible to explicitly control the W and H
- we shall make it possible to explicitly disable the search toolbar
- - we shall make it possible to explicitly disable the scale bar

## Other useful information
I would also double check what Google Maps allows and then make a comprehensive proposal.

**Comment by simboss** [comment]
@tdipisa let's discuss this for the near future.

**Comment by tdipisa** [comment]
@simboss thank you for reporting this.

>If you open this page and scroll to the bottom there is a MapStore map embedde; in incognito I noticed that embedding does not work. Ok, maybe it is normal that it does not work but at least give me a nice message. That said, I don't think it should simply crash like this, we have got to make it work.

I think you forgot to include the link to the page: can you please provide it so that I can check?
I only tried it locally: are you referring to the fact that MS never stops loading?

>Same map as above, I click on the icon to open it in a larger window and boom "Ops, Something has gone wrong.", nice...

I've reproduced it locally. I will open an issue.

>if you check what you can do with other populare similar services we are way behind. If you check what uMap can do (see at the bottom of this page), there is room for improvement:

Few questions for this below:

>we shall be able to disable muse scrolling and add zoom in/out as the scrolling makes it difficult to embed in some pages

Let's see first what we can do by configuration for this. @offtherailz can you do a first check please and report back here in the issue your feedback?

>we need the fullscreen button

I think it is a matter of configuration but @offtherailz can confirm this.

>we shall make it possible to explicitly control the W and H

What do you mean precisely?

>we shall make it possible to explicitly disable the search toolbar

What do you mean? There is already a button to open close the search bar.

>we shall make it possible to explicitly enable/disable

explicitly enable/disable what?
