### ISSUE TITLE
Create an intermediate step for project system update

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7088]
## Description
New project is not finalized. For this reason we should create an intermediate release, with the old project system and this new as "new method, still in beta". 

Things to do:
- [x] Verify that the old project system is fully working it should. Here only the things that I noticed: 
- [x] Fix the following **bugs** (for my testings, during training tests)
    - [x] #7118
- [x] #7117
- [x] (not strictily mandatory, but suggested) enable data-dir working in mapstore product - transparently #7102

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
@offtherailz the test of this Epic is up to you and not @ElenaGallo
