### ISSUE TITLE
Display settings panel options issue

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7379]
## Description

From the Display settings panel on **Map**, **Second step of Context widget** and **GeoStory- Map Editor**,  the following options cause an error:
- Format
- Tile size
- Opacity
- Trasparent
- Cache options
- Single tile
- Localized style

## How to reproduce

-  Open a map
- Select a layer 
- Click on Settings > Display
- Change the Format or Tile size or the Opacity 
or
- Enable/disable the Trasparent or the Cache options or the Single tile or the Localized style

*Expected Result*

It is possible to Change the Format or Tile size or the Opacity  and Enable/disable the Trasparent or the Cache options or the Single tile or the Localized style

*Current Result*

By changing or enabling/disabling the options listed above, the gray error page is displayed

Error on console:
> mapstore2.js?8beef3696d5cd156e798:2 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Object.onChange (mapstore2.js?8beef3696d5cd156e798:2)
    at onChange (mapstore2.js?8beef3696d5cd156e798:2)
    at Object.m (mapstore2.js?8beef3696d5cd156e798:2)
    at _ (mapstore2.js?8beef3696d5cd156e798:2)
    at mapstore2.js?8beef3696d5cd156e798:2
    at C (mapstore2.js?8beef3696d5cd156e798:2)
    at M (mapstore2.js?8beef3696d5cd156e798:2)
    at Array.forEach (<anonymous>)
    at O (mapstore2.js?8beef3696d5cd156e798:2)
    at P (mapstore2.js?8beef3696d5cd156e798:2)
    at gn (mapstore2.js?8beef3696d5cd156e798:2)
    at ce (mapstore2.js?8beef3696d5cd156e798:2)
    at En (mapstore2.js?8beef3696d5cd156e798:2)
    at Sn (mapstore2.js?8beef3696d5cd156e798:2)
    at xn (mapstore2.js?8beef3696d5cd156e798:2)
    at t.unstable_runWithPriority (mapstore2.js?8beef3696d5cd156e798:2)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@ElenaGallo I cannot test it in DEV now, but it seems working now in QA. Can you please confirm?

**Comment by ElenaGallo** [comment]
@tdipisa  I can confirm that on QA it works

**Comment by tdipisa** [comment]
@tonym3nsa please check the following then

>@tonym3nsa If confirmed, can you please check at least if there has been a recent commit in QA that fixed that regression? Otherwise, I'm wondering why this issue is open

Let's wait to test it on DEV again before closing this issue.

**Comment by tdipisa** [comment]
Going "a little bit" further it seems that the Layer Settings is completely buggy. The description of this issue does not seem to do justice to the real problem. Please try all the following functionalities of layer settings:

- [ ] Title Translations: try to put a translation for at least two languages
- [ ] Description: give the focus to the description area and then remove the focus
- [ ] Tooltip: try change tooltip content
- [ ] Placement: try to change the tooltip placement
- [ ] Tile size: try to change the tile size, then close layer settings then reopen the layer settings
- [ ] Opacity: try to change the layer opacity, then close layer settings then reopen the layer settings
- [ ] Single tile: enable single tile option, then close layer settings then reopen the layer settings
- [ ] Info format: try to change info format, then close layer settings then reopen the layer settings. I don't know if related to #7361 
- [ ] @ElenaGallo, please do some more tests on this tool to make sure you haven't missed anything else
 
@ElenaGallo all of the above must be caught during tests
@tonym3nsa all the above are important regressions, I hope all of these can be fixed quickly and easily without breaking other things

@offtherailz we have to clearly understand why all of these regressions have been introduced.

**Comment by offtherailz** [comment]
The regression has been cause by: 
Issue #7361; feature info selector fixed (#7387)
checked using `git bisect`. In the `good` tasks, I had an error in console, but not a complete failure.
