### ISSUE TITLE
Add support for importing / exporting dashboards, stories and contexts

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#7439]
## Description

let's add import/export tool also for other resources different from the Map
## Acceptance criteria

Add in the related burger menu the possibility to 

- [x] import a dashboard (from json)
- [x] export a dashboard (to json)
- [x] import a geostory (from json)
- [x] export a geostory (to json)
- [ ] import a context (from json)
- [ ] export a context (to json)
