### ISSUE TITLE
Time Line enhancements - full support of time values as intervals

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#7958]
For multidimensional Layers, marked as multidimensional in Geoserver, when time dimension is enabled it is possible to select an Attribute and an End Attribute, only Attribute is currently considered by MapStore when setting up the TimeLine component, as a consequence it is not entirely possible to analyse time based domains data in a range between Attribute and End Attribute. The time analysis is performed on single 'punctual' time values along the time line. The objective that we want to accomplish is to have 'time intervals' represented data on the timeline, this means time will no longer be only a time instant in timeline but it could also be managed as a time range, an interval between `Attribute` and `End Attribute` for each record of the multidimensional attribute, in this specific case time.

Freshdesk original ticket: http://vlaanderen.geo-solutions.it/support/tickets/46980)

The implementation of this new approach to time based layer analysis will have implications:

1. How the timeline component will display the histograms representing the data occurrences for each time interval in the total time range. (front-end)
2. How to compute histograms when we have time interval analysis rather than time instants values (back-end)
3. How to handle the different response from the server when the analysis is based on time intervals (front-end)

Moreover, in details the implications regarding the front-end implementations will have to take into account different user/data cases scenarios that will be collected in the issues within this epic (i.e. overlapping intervals, time range analysis window snapping, etc.) 

# Acceptance criteria

- [x] As a user I want to add to the map a layer from a GeoServer **with WMTS Multidim extension** that is configured with start and end attributes for time dimension. 
- [x] When I add the layer the timeline plugins shows the values of values of time intervals for the layer as horizontal bars. If the time intervals overlap the timeline section dedicated to the layer should expand vertically to allow a vertical stacking of the bars, in order to show all the values clearly.
- [x] When I click on the timeline with the snapping active, the cursor will be placed to the nearest time that is a **start point or an end point** of the interval.  
- [x] The animations and the forward-backward buttons (with snap to layer active) will snap to **start time** and **end time** of each interval, according to user choice. 
- [x] If more that 20 elements are present in the same layer for the given interval, the histogram will be shown instead (as it is now). 

![timeline-intervals1](https://user-images.githubusercontent.com/1279510/159245595-3dbf4f33-040f-41b7-a308-189c10674140.jpg)

# Other related tasks 
- Back-end work to return intervals from start/end attribute https://github.com/geosolutions-it/support/issues/1943

# Analysis and development considerations

## Snap and Animation

Snap and animation now work with DescribeDomains calls. Support to interval from the back-end (and possible interval values returned by the service) should be supported and parsed by the client to provide both the functionalities as they are working now. We need to define a policy for snapping to intervals and selecting the animations time values. These are the possibilities: 

**Snap:**
1.  snap start time, without any configuration. 
2.  snap to start or end time (nearest).
3.  snap to the center of the interval.
4.  snap to start, center or end (configurable from UI). 

For the moment we should "snap to **start or end** time of the interval (2nd point)" leaving space for the evolution of this. 

**Animation**:

In case of animation, snapping on start time seems to be the simplest solution to support time intervals. For the moment we should support this. Other options should be configurable (e.g. center, end).

## Backend service

The WMTS multidim extension must support time interval (this has a separate issue for GeoServer). 

It is important that the back-end service **must** return the values even if the start-end are outside the range requested but the interval overlaps the interval requested. This to properly show the time values on the timeline.

## UI 

Multiple interval occurrences may  have 'overlapping' time intervals, these could be represented with stacked time interval bars, this design may also require to change the height of the timeline component to accommodate the vertically stacked interval bars, height could be dynamic, according to the number of occurrences of interval for a given time instant.

## Performances

Now there is a limit of 20 items per layer to limit the rendering of timeline and avoid perfomance issues due to the continuous re-rendering of the items. 

We could keep this limit with the new interface.

**Comment by offtherailz** [comment]
For snapping to end or middle, we have a problem that can be solved only with some improvements on the back-end. 

Snapping and animation use DescribeDomains filtered in a particular direction. Anyway the current filtering on server side seems to be done by start time. 

This makes impossible to get the nearest end value quering the actual UI (without having the full dataset)
 See the example below: 
![Sync about Timeline with intervals - snap end issue](https://user-images.githubusercontent.com/1279510/165757148-5a753d82-2aae-4a1e-9d47-94dab56404ac.png)

The vertical bar is where the user clicked. MapStore do a request for each direction to get the nearest element in both direction.
The server return the nearest start time, that is incorrect. In the left direction, it gets the wrong element, in the right direction isn't able to get anything, because start-time is placed before the clicked point.


Also the animation is affected by this issue, expecially when selecting a start-end interval. Filtering is applied tp start time that may be outside the interval required.


I suggest to add a paramter filterBy start|end|middle (start as default) that makes this snapping possible, and also animation frames retrival working as expected.

Note: the interval will be returned full. The only purpose of the new parameter is to select witch of the times have to be used for filtering.

**Comment by ale-cristofori** [comment]
The development of this feature is encountering some issues when trying to implement the snap to an `endDate` record. Also, the implementation of such feature has brought out some complexities that impact the overall time needed to develop this feature.

ISSUES:
1. Backward/Forward buttons when `endDate` snapping is on will make the timeline go out of scale, at some point dates received is out of the dates that should be in the correct domain. The timeline cursor disappears, this behaviour is inconsistent and we noticed with @offtherailz tends to happen more frequently when the buttons are clicked continually in a fast way. Anyway needs more investigation.
2.  Customer provided some test data, once the layer is loaded on MapStore, the timeline and its tools are correctly displayed but the timeline bars are intermittently visible. When the timeline is clicked/moved they appear, to then disappear right after the mouse is released. This happens only with customer provided data. On top of it, if the cursors is moved the all application crashes. Again, this bug is quite inconsistent and I have not been able yet to identify what triggers the crash. As for the bars disappearing, I had a look at the DOM and it looks like the vis-timeline does not load data at all.

**Comment by ale-cristofori** [comment]
@tdipisa @offtherailz 

The data that the customer supplied is quite peculiar, since it contains no "intermediate" start point interval.
![image](https://user-images.githubusercontent.com/14953970/167600572-db90a4a6-25df-4b3d-a3f7-e7260f3f3e6f.png)

This causes issues when trying to enable snapping, since at the moment is only set to work with start values. This issue could potentially be overcome by checking the endPoints too. I have an idea on how to proceed with this issue

Secondly, this also causes issues when setting up a time frame for animations the timeline component relies on an object called `rangeItems` having a `start` and `end` property. Those properties are missing using the customer data based dataset. maybe for the same reason explained above.

Could anyone help me with these two issues?

**Comment by ElenaGallo** [comment]
@tdipisa @ale-cristofori  I only noticed a problem with a layer with 'instants' that I have reposed here:
https://github.com/geosolutions-it/MapStore2/issues/8206#issue-1240104246
