### ISSUE TITLE
Support of vector geometries in Cesium Map

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8100]
## Description

Perform an analysis over different data formats such as GeoJSON (also via WFS) to represent requested types of geometries such as 3D lines and 3D points. 

## Acceptance criteria

- [x] Support of imported vector layers in Cesium
- [x] Support of WFS layers in Cesium

**Comment by allyoucanmap** [comment]
First implementation of WFS and vector in Cesium will include the direct rendering of all features available similar to OpenLayers and Leaflet so it expect a small/medium set of features.

Screenshots:

**WFS**

![image](https://user-images.githubusercontent.com/19175505/166206507-514b21ef-5ad2-4cce-b8f6-fa6aaf8a5b88.png)

**Shapefile**

![image](https://user-images.githubusercontent.com/19175505/166206781-de01404f-ea66-454b-8094-169143fbe5fb.png)

Possible improvements:

- [ ] Add dynamic load of features and simplification based on the view to improve performance. This could be done by adding a flag that allows the user to enable this functionality. I made a test but the worflow is not always consistent and fast (to be reviewed)
- [ ] Verify positioning of geometries on terrain provider
- [x] restore `depthTestAgainstTerrain` to false to ensure features are always visible
- [ ] Cesium sets a GeoJSON feature to a specific height if the features describe the correct height in the coordinates array per vertex. This height is `per vertext` different from the height described on a style rule available in cesium. Maybe this could be interesting addition to the Annotation editor for the coordinates.

Workflow missing in Cesium available on other map type:

- [ ] Import local data not available in cesium (shapefile, geojson, ..)
- [ ] Get feature info not working for WFS in cesium
- [ ] Annotations are not listed in the TOC for Cesium viewer
