### ISSUE TITLE
GeoStore improvements

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#865]
The following issues must be resolved on GeoStore

- [x] geosolutions-it/GeoStore#140 - Base64 decoder (needed for #852)
- [x] geosolutions-it/GeoStore#141 - Pagination (needed for #864 )
- [x] geosolutions-it/GeoStore#142 - Case Sensitive Search (needed for #864 )
