### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9001]
## Description

The target of this issue is to automate the release process with github actions to speed up the process as much as possible. 

###  Continuous integration 

The first phase is to automate the continuous integration on the master and release branches, to deliver on maven repository all the latest versions of the packages automatically. 

This has been done on : 
  - [x] GeoStore
  - [x] Http proxy
  - [x] MapFish Print (custom)
  - [x] MapStore

Actually `MapStoreExtension` project do not deliver anything, so no CI is necessary. Only a continuous test and build of the project is implemented.

### Release Process

After a first round, I was able to automate release process of main java  dependencies  (GeoStore/HttpProxy/MapFish-Print). 

They all follow all the same strategy, made of 2 main phases: 

#### 1. Cut the new brach

In this phase the steps to do are:

- A new branch named <MAJOR_VERSION_NUMBER>.xx is created
- On the main branch (`master`) version of `pom.xml` modules (SNAPSHOT) are increased

Example:

```mermaid
gitGraph
    commit
    branch 2.0.x
    checkout main
    commit id: "Increase Snapshots to 2.1-SNAPSHOT" type:HIGHLIGHT
    checkout 2.0.x
    commit id: "Fix 1"
``` 

This procedure of branch creation and version increase (via Pull request) is realized with the `cut-major-branch.yml` Github Workflow in the projects:
  - [x] GeoStore
  - [x] Http proxy
  - [x] MapFish Print (custom) 

##### MapStore & MapstoreExtension

MapStore requires some additional steps to be automated. The intention is to uniform MapStore to the other project, removing the exceptions as much as possible. 

In particular for `MapStore`: 
- Create the documentation (manual)
- Increase versions on Master should be automated
- `package.json` have to be updated too. 
- Project template system requires some manual change.
- Need to fix the dependencies to NO-SNAPSHOT for GeoStore/HTTPProxy/MapFishPrint  to the desired **on the release branch** and **before** the effective release. Also for this we need a strategy to be defined. 

On `MapStoreExtension` we need to define a strategy to properly update the version continuously.

### 2. Release

When the branch cut is ready to be released in a certain version, the procedure requires to: 

- Fix version on release branch
- Tag the version with `v<VERSION-NUMBER>`
- restore SNAPSHOTS
- Create the release on github on the tagged version

Example (Excluded the release creation): 

```mermaid
gitGraph
    commit
    branch 2.0.x
    commit id: "Fix 1"
    commit id: "Set Versions to 2.1.0" tag: "v2.1.0" type:HIGHLIGHT
    commit id: "Restore 2.1-SNAPSHOT" type:HIGHLIGHT
    commit id: "Fix 2"
    commit id: "Set Versions to 2.1.1" tag: "v2.1.1"
    commit id: "Restore 2.1-SNAPSHOT (2)"
``` 

This procedure is realized in the 3 projects with the `release` Process in:
  - [x] GeoStore
  - [x] Http proxy
  - [x] MapFish Print (custom) 

For `MapStore` we need some additional steps: 
- Changelog have to be updated on master and stable branches.
- The release should be created as draft, so the admins can manually prepare the text, with an initial draft containing the links generated from a template
- project system requires some additional step (set pom.xml of template)
- (Remove hard-coded version steps for project creation script. See here: #9002 ) 
- `package.json` have to be updated too. 
- `documentation` on `readthedocs.io` have to be created. 
- `docker` have to be properly published and linked in the release
- Upload artifact in the release
- `deploy on stable should be done.
- Jenkins jobs have to be a little modified (e.g. removing release job, replaced by this automation, while stable deploy should be applied on the tagged commit, instead of the branch).

More details or a double check about this list can be done by checking the release procedure of MapStore. 

Actually there is a pending draft PR #8966  that partially implement release build and upload of the artifact, including release creation. It have to be aligned to the other procedures, including the commits for snaphot, tag creation etc...

Moreover some proposed changes #9002 remove hard-coded things regarding the project creation system, making the release process easier

We can decide to avoid certain steps (e.g. Changelog generation, that is a list of issues that can be recovered also in releases) to simplify more.  

At the end `MapStoreExtension` should so align the submodule to the tagged MapStore release above and properly linked too.
This should not be too hard to do, even if it requires a little more work.

## MapStoreExtension

```[tasklist]
### Tasks
- [x] **geostore**: Automate cut release branch 
- [x] **geostore** automate deploy of snapshots
- [x] **geostore** automate release creation
- [x] **mapfish-print**: Automate cut release branch 
- [x] **mapfish-print** automate deploy of snapshots
- [x] **mapfish-print** automate release creation
- [x] **http-proxy**: Automate cut release branch 
- [x] **http-proxy** automate deploy of snapshots
- [x] **http-proxy** automate release creation
- [ ] **MapStore**: Automate cut release branch 
- [x] **MapStore** automate deploy of snapshots
- [ ] **MapStore** automate release creation
- [ ] **MapStoreExtension**: Automate cut release branch 
- [x] **MapStoreExtension** automate deploy of snapshots
- [ ] **MapStoreExtension** automate release creation
```
Pending tasks details
-  **MapStore**: Automate cut release branch requies to:
    - properly bump all versions
    - pay attention to the versions done
- [ ] **MapStore** automate release creation: requires to: https://github.com/geosolutions-it/MapStore2/pull/8966
    - Remove some hard coded operations ( https://github.com/geosolutions-it/MapStore2/pull/9002 )
    - make sure to have new versions of previous project available 
    - Handle MapStoreExtension

**Comment by offtherailz** [comment]
Considerations about pending release automations (WIP comment)

## MapStore Extension 

- Cut release branch - > should be evaluated with the submodule update in general (notice that the new project system removes the submodule dependency, simplifying the whole process. We should evaluate to do this instead)
- Create release: it means to align to the stable version of mapstore and create the release. **note** a link is created on mapstore release too. Evaluate how to handle this linking

## MapStore

- Cut release branch.
   -  Need to evaluate the version of various version updates (WIP) 
       - use mvn commands may help. 
       - The manual update of project is not very easy to automate. Possible solutions could be
           - String replacement
           - Using `archetype`
           - Running the command on the template pom too (error prone)
   - 
-  Create release: 
   - Generate and commit changelog (on master and release branch
   - Commit fixed versions in pom (commands help)

**Comment by MV88** [comment]
@tdipisa @offtherailz can this stay closed?

**Comment by tdipisa** [comment]
no @MV88 some tasks still need to be done to complete.
