### ISSUE TITLE
GetMap format list in GetCapabilities not respected

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9031]
## Description

From https://github.com/georchestra/mapstore2-georchestra/issues/301

whatever the server says in the getcapabilities, it seems mapstore hardcodes the image format list in several places:

* https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/background/BackgroundDialog.jsx#L66
* https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/catalog/Catalog.jsx#L115
* https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/MetadataExplorer.jsx#L126
* https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/TMSUtils.js#L10
* https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/TOC/fragments/settings/Display.jsx#L116

i know (from the doc in https://github.com/geosolutions-it/MapStore2/blob/master/docs/user-guide/catalog.md#advanced-settings-1) that one can configure that per catalog service (well, in the UI one can only remove some formats from the 'default list', but i guess in the .js its configurable more finely), and i guess this hardcoded list comes from the default formats supported by geoserver (which mapstore2 is developed/tested against, other servers being less tested..) but could we *at least* prune the list from the formats not listed in the servers' GetCapabilities ?

for example mapserver has this:
```
<GetMap>
<Format>image/png</Format>
<Format>image/jpeg</Format>
<Format>image/png; mode=8bit</Format>
<Format>image/vnd.jpeg-png</Format>
<Format>image/vnd.jpeg-png8</Format>
<Format>application/x-pdf</Format>
<Format>image/svg+xml</Format>
<Format>image/tiff</Format>
<Format>application/vnd.google-earth.kml+xml</Format>
<Format>application/vnd.google-earth.kmz</Format>
<Format>application/x-protobuf</Format>
<Format>application/json</Format>
```
so in the mapstore UI if one selects `image/gif` or `image/png8` the layer breaks.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
This other issue should be included
```[tasklist]
### Tasks
- [ ] #8906
```
