### ISSUE TITLE
Annotation support for 3D

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9094]
## Description

From 2022.02.00 it is already possible to visualize existing annotations (created in 2D) when the user switch to 3D mode.
There are anyway some visualization options still not supported (like _start/end point_ for a line) that could be implemented with the aim to completely align the annotation capabilities for 3D with the ones available in 2D.

## Acceptance criteria

This development include the support for the editing of the annotations in 3D mode that's still unsupported:
- UI change not much (TBD)
- Refactor of the draw tool for the 3D
- Real time editing directly on map for the 3D
- Styling review (TBD)

```[tasklist]
### Tasks
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9355
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9352
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9396
```

**Comment by allyoucanmap** [comment]
see description of #9152
