### ISSUE TITLE
Support for fields aliases in MapStore tools

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9128]
Given the support in #9099, we should support the aliases in the following tools of MapStore.

```[tasklist]
### Tasks
- [x] **Feature Grid** Integrate in column names and In columns visibility selector. Included in #9125
- [x] https://github.com/geosolutions-it/MapStore2/issues/9142
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9143
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9144
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9141
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9150
```
