### ISSUE TITLE
Issues after upgrading OpenLayers

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9302]
## Description

After upgrading OpenLayer, these are the problems:

**Attribute Table**
- Selecting a feature on the map with the Quick Filter selects the features but does not highlight them on the map. 
![filter feature](https://github.com/geosolutions-it/MapStore2/assets/56537133/a8ff3589-3ddd-40f6-bfef-40fac5ee545f)

- Clicking the Zoom to feature, does not highlight feature on the map.
![zoom to feature](https://github.com/geosolutions-it/MapStore2/assets/56537133/bcaea8ef-09e7-4bdc-87dd-3215c1787731)

- Geometry cannot be drawn using snapping.
![snapping](https://github.com/geosolutions-it/MapStore2/assets/56537133/50570e16-cd27-496b-934b-88f21f0a3467)

**Print tool**
- The map is not visible on the printed preview and pdf.
![print](https://github.com/geosolutions-it/MapStore2/assets/56537133/c2594030-3033-45c2-998c-4e7d20df5188)

**Graticule**
- Only the first comment of #9292 is still present 

**Context**
- I don't know if it is related to this update but the Edit button in the Attribute Table is no longer visible in step two of the wizard and then in the context (even if the **Disable editing on Attribute table** button in the layer settings is not enabled, #9180) 
![edit button](https://github.com/geosolutions-it/MapStore2/assets/56537133/cca54ba1-2a58-4972-92fb-81a334788489)

```[tasklist]
### Tasks
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9348
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9346
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9274
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9363
- [ ] https://github.com/geosolutions-it/MapStore2/issues/9366
```

**Comment by allyoucanmap** [comment]
@ElenaGallo @tdipisa 

> - Selecting a feature on the map with the Quick Filter selects the features but does not highlight them on the map.
> - Clicking the Zoom to feature, does not highlight feature on the map.

Has been solved with #9274

> - Geometry cannot be drawn using snapping.

I'm not able to reproduce this (I need a feedback on this)

> Print tool
> 
> - The map is not visible on the printed preview and pdf.

I'm going to open a separate issue

> Graticule
> 
> - Only the first comment of https://github.com/geosolutions-it/MapStore2/issues/9292 is still present

This one was not introduced by the upgrade and it was already there

> Context
> 
> - I don't know if it is related to this update but the Edit button in the Attribute Table is no longer visible in step two of the wizard and then in the context (even if the Disable editing on Attribute table button in the layer settings is not enabled, https://github.com/geosolutions-it/MapStore2/issues/9180)

This one is not related to the upgrade and it seems that we decided to include the FeatureEditor in context creator and disable the editing for all users in this PR https://github.com/geosolutions-it/MapStore2/pull/9262. There is a comment in the code:

```js
{
    "name": "FeatureEditor",
    "overrides": {
        "cfg": {
            // To forcefully hide edit feature for all user roles
            editingAllowedRoles: []
        }
    }
},
```

**Comment by ElenaGallo** [comment]
@allyoucanmap 

> - Geometry cannot be drawn using snapping.
>
> I'm not able to reproduce this (I need a feedback on this)

I still can't use snapping to create new geometry
