### ISSUE TITLE
Alternative layouts for the TOC

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#9982]
## Description

This issue collects all the needed changes to review the table of content:

## Acceptance criteria

- [ ] Refactor of TOC components, plugin and styling
- [ ] Refactor of drag and drop of components
- [ ] Refactor of filtering system
- [ ] Improve title visibility

## Other useful information

```[tasklist]
### Task to take into account in the development
- [ ] #8918
- [ ] #9430
- [ ] #8953
- [ ] #8471
- [ ] #4255
- [ ] https://github.com/GeoNode/geonode-mapstore-client/issues/1265
```
